# Generated by Django 5.0 on 2023-12-15 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rickAndMorty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
